/**
 * server-lens install — generate cron/systemd files from server-lens.toml
 * @see docs/pipeline.md
 */

import { loadConfig } from "../config/config-loader";
import { writeFileSync, mkdirSync, existsSync, chmodSync } from "fs";
import { dirname } from "path";

function tryWrite(path: string, content: string, mode?: number): boolean {
  try {
    const dir = dirname(path);
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
    writeFileSync(path, content, { mode });
    return true;
  } catch {
    return false;
  }
}

export async function runInstall(args: string[]): Promise<void> {
  const useSystemd = args.includes("--systemd");
  const dryRun = args.includes("--dry-run");
  const config = loadConfig();
  const schedule = config.settings.scan_schedule;
  const binPath = "/usr/local/bin/server-lens";

  console.log("");
  console.log("  server-lens install");
  console.log(`  Schedule: ${schedule}`);
  console.log(`  Binary:   ${binPath}`);
  console.log("");

  const files: Array<{ path: string; content: string; mode?: number; description: string }> = [];

  if (useSystemd) {
    // --- systemd timer + service ---
    const serviceContent = `[Unit]
Description=server-lens scan
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=${binPath} scan --quiet
User=root
StandardOutput=journal
StandardError=journal
SyslogIdentifier=server-lens
`;
    const timerContent = `[Unit]
Description=server-lens scheduled scan
After=network-online.target

[Timer]
OnCalendar=${toSystemdCalendar(schedule)}
Persistent=true

[Install]
WantedBy=timers.target
`;
    files.push({
      path: "/etc/systemd/system/server-lens.service",
      content: serviceContent,
      description: "systemd service unit",
    });
    files.push({
      path: "/etc/systemd/system/server-lens.timer",
      content: timerContent,
      description: "systemd timer unit",
    });
  } else {
    // --- cron ---
    const cronContent = `# server-lens scan schedule (generated by server-lens install)
# Edit schedule in ${config.configPath} under [settings].scan_schedule
${schedule} root ${binPath} scan --quiet 2>&1 | logger -t server-lens
`;
    files.push({
      path: "/etc/cron.d/server-lens",
      content: cronContent,
      description: "cron schedule",
    });
  }

  // --- MOTD hook ---
  const motdContent = `#!/bin/bash
# server-lens MOTD hook — instant display mode, no network calls
exec ${binPath}
`;
  files.push({
    path: "/etc/update-motd.d/99-server-lens",
    content: motdContent,
    mode: 0o755,
    description: "MOTD hook (SSH welcome screen)",
  });

  // --- Config dir hint ---
  const etcConfigPath = "/etc/server-lens/server-lens.toml";

  if (dryRun) {
    console.log("  [dry-run] Files that would be written:");
    for (const f of files) {
      console.log(`    ${f.path}  (${f.description})`);
    }
    console.log("");
    console.log("  [dry-run] Config should be at:", etcConfigPath);
    console.log("");
    return;
  }

  let anyFailed = false;
  for (const f of files) {
    const ok = tryWrite(f.path, f.content, f.mode);
    if (ok) {
      console.log(`  ✓ ${f.path}`);
    } else {
      console.log(`  ✗ ${f.path}  (permission denied — run as root or copy manually)`);
      console.log("");
      console.log(`    --- ${f.description} ---`);
      console.log(f.content.split("\n").map((l) => "    " + l).join("\n"));
      anyFailed = true;
    }
  }

  if (useSystemd && !anyFailed) {
    console.log("");
    console.log("  Enable and start the timer:");
    console.log("    systemctl daemon-reload");
    console.log("    systemctl enable --now server-lens.timer");
  }

  if (!existsSync(etcConfigPath)) {
    console.log("");
    console.log("  Config not found at", etcConfigPath);
    console.log("  Copy example config:");
    console.log(`    mkdir -p /etc/server-lens && cp server-lens.toml ${etcConfigPath}`);
  }

  console.log("");
  console.log("  Run your first scan:");
  console.log("    server-lens scan --now");
  console.log("");
}

/** Convert a cron expression to a systemd OnCalendar value (best-effort) */
function toSystemdCalendar(cron: string): string {
  // Simple conversion for common patterns
  const parts = cron.trim().split(/\s+/);
  if (parts.length !== 5) return `*-*-* *:*:00 # from cron: ${cron}`;
  const [min, hour, dom, mon, dow] = parts;

  // Every N hours: "0 */6 * * *" -> "*-*-* 00,06,12,18:00:00"
  if (dom === "*" && mon === "*" && dow === "*") {
    if (hour.startsWith("*/")) {
      const n = parseInt(hour.slice(2));
      const hours: number[] = [];
      for (let h = 0; h < 24; h += n) hours.push(h);
      return `*-*-* ${hours.map((h) => h.toString().padStart(2, "0")).join(",")}:${min.padStart(2, "0")}:00`;
    }
    if (hour !== "*" && min !== "*") {
      return `*-*-* ${hour.padStart(2, "0")}:${min.padStart(2, "0")}:00`;
    }
  }
  return `*-*-* *:${min}:00  # from cron: ${cron}`;
}
